[package]
name = "raytracer"
version = "0.1.0"
authors = ["olege"]
edition = "2018"

[lib]
name = "raytracer"
path = "src/lib.rs"

[dependencies]
cgmath = "*"
image = "*"
rand = "*"
rand_distr = "*"

[dev-dependencies]
criterion = "*"

[[bench]]
name = "benchmarks"
harness = false